import { 
  FileJson, 
  FileType, 
  FileText, 
  Image as ImageIcon, 
  FileCode, 
  Table, 
  FileDigit,
  Layout,
  Layers,
  Minimize,
  Maximize
} from "lucide-react";

export type Category = "Documents" | "Data" | "Images" | "Tools";

export interface ConverterConfig {
  id: string;
  title: string;
  category: Category;
  description: string;
  icon: any;
  accept: string;
  extensions: string[];
  maxSize: number; // in bytes
  targetExt: string;
  contentType: string;
}

export const CONVERTERS: ConverterConfig[] = [
  // DATA CONVERTERS
  {
    id: "excel-to-json",
    title: "Excel to JSON",
    category: "Data",
    description: "Convert spreadsheet data to JSON format instantly.",
    icon: FileJson,
    accept: ".xlsx,.xls",
    extensions: ["xlsx", "xls"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "json",
    contentType: "application/json",
  },
  {
    id: "json-to-excel",
    title: "JSON to Excel",
    category: "Data",
    description: "Generate Excel files from JSON arrays.",
    icon: Table,
    accept: ".json",
    extensions: ["json"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "xlsx",
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  },
  {
    id: "csv-to-json",
    title: "CSV to JSON",
    category: "Data",
    description: "Convert CSV files into JSON format instantly.",
    icon: FileJson,
    accept: ".csv",
    extensions: ["csv"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "json",
    contentType: "application/json",
  },
  {
    id: "json-to-csv",
    title: "JSON to CSV",
    category: "Data",
    description: "Convert JSON data back to CSV format.",
    icon: FileDigit,
    accept: ".json",
    extensions: ["json"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "csv",
    contentType: "text/csv",
  },
  {
    id: "xml-to-json",
    title: "XML to JSON",
    category: "Data",
    description: "Convert XML data structures into JSON format.",
    icon: FileCode,
    accept: ".xml",
    extensions: ["xml"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "json",
    contentType: "application/json",
  },
  {
    id: "json-to-xml",
    title: "JSON to XML",
    category: "Data",
    description: "Convert JSON objects into XML format.",
    icon: FileCode,
    accept: ".json",
    extensions: ["json"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "xml",
    contentType: "application/xml",
  },
  {
    id: "yaml-to-json",
    title: "YAML to JSON",
    category: "Data",
    description: "Convert YAML configuration files to JSON.",
    icon: FileCode,
    accept: ".yaml,.yml",
    extensions: ["yaml", "yml"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "json",
    contentType: "application/json",
  },
  {
    id: "pdf-to-csv",
    title: "PDF to CSV",
    category: "Data",
    description: "Extract PDF table data into CSV format.",
    icon: FileDigit,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "csv",
    contentType: "text/csv",
  },
  {
    id: "excel-to-csv",
    title: "Excel to CSV",
    category: "Data",
    description: "Convert Excel spreadsheets to CSV format.",
    icon: FileDigit,
    accept: ".xlsx,.xls",
    extensions: ["xlsx", "xls"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "csv",
    contentType: "text/csv",
  },
  
  // DOCUMENT CONVERTERS
  {
    id: "pdf-to-docx",
    title: "PDF to DOCX",
    category: "Documents",
    description: "Convert PDF files into editable Word documents.",
    icon: FileType,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "docx",
    contentType: "application/vnd.openxmlformats-officedocument.wordprocessingml.document",
  },
  {
    id: "docx-to-pdf",
    title: "DOCX to PDF",
    category: "Documents",
    description: "Securely convert Word documents to PDF.",
    icon: FileText,
    accept: ".docx",
    extensions: ["docx"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  },
  {
    id: "pdf-to-txt",
    title: "PDF to Text",
    category: "Documents",
    description: "Extract plain text from PDF documents.",
    icon: FileText,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "txt",
    contentType: "text/plain",
  },
  {
    id: "html-to-pdf",
    title: "HTML to PDF",
    category: "Documents",
    description: "Convert web pages or HTML files to PDF.",
    icon: Layout,
    accept: ".html,.htm",
    extensions: ["html", "htm"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  },
  {
    id: "jpg-to-pdf",
    title: "JPG to PDF",
    category: "Documents",
    description: "Convert images into a single PDF document.",
    icon: FileText,
    accept: ".jpg,.jpeg,.png",
    extensions: ["jpg", "jpeg", "png"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  },
  {
    id: "png-to-pdf",
    title: "PNG to PDF",
    category: "Documents",
    description: "Convert PNG images into a PDF document.",
    icon: FileText,
    accept: ".png",
    extensions: ["png"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  },
  {
    id: "excel-to-pdf",
    title: "Excel to PDF",
    category: "Documents",
    description: "Convert spreadsheets directly to PDF format.",
    icon: FileText,
    accept: ".xlsx,.xls",
    extensions: ["xlsx", "xls"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  },
  {
    id: "pdf-to-jpg",
    title: "PDF to JPG",
    category: "Documents",
    description: "Convert PDF pages into JPG images.",
    icon: ImageIcon,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "jpg",
    contentType: "image/jpeg",
  },
  {
    id: "pdf-to-excel",
    title: "PDF to Excel",
    category: "Documents",
    description: "Extract data from PDF tables to Excel.",
    icon: Table,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "xlsx",
    contentType: "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
  },

  // IMAGE CONVERTERS
  {
    id: "svg-to-png",
    title: "SVG to PNG",
    category: "Images",
    description: "Rasterize vector graphics to transparent PNGs.",
    icon: ImageIcon,
    accept: ".svg",
    extensions: ["svg"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "png",
    contentType: "image/png",
  },
  {
    id: "png-to-svg",
    title: "PNG to SVG",
    category: "Images",
    description: "Wrap PNG images into SVG containers.",
    icon: ImageIcon,
    accept: ".png",
    extensions: ["png"],
    maxSize: 5 * 1024 * 1024,
    targetExt: "svg",
    contentType: "image/svg+xml",
  },
  {
    id: "jpg-to-png",
    title: "JPG to PNG",
    category: "Images",
    description: "Convert JPEG images to PNG format.",
    icon: ImageIcon,
    accept: ".jpg,.jpeg",
    extensions: ["jpg", "jpeg"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "png",
    contentType: "image/png",
  },
  {
    id: "png-to-jpg",
    title: "PNG to JPG",
    category: "Images",
    description: "Convert PNG images to JPG format.",
    icon: ImageIcon,
    accept: ".png",
    extensions: ["png"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "jpg",
    contentType: "image/jpeg",
  },
  {
    id: "webp-to-png",
    title: "WEBP to PNG",
    category: "Images",
    description: "Convert modern WEBP images to PNG.",
    icon: ImageIcon,
    accept: ".webp",
    extensions: ["webp"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "png",
    contentType: "image/png",
  },
  {
    id: "webp-to-jpg",
    title: "WEBP to JPG",
    category: "Images",
    description: "Convert WEBP images to JPG format.",
    icon: ImageIcon,
    accept: ".webp",
    extensions: ["webp"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "jpg",
    contentType: "image/jpeg",
  },
  {
    id: "heic-to-jpg",
    title: "HEIC to JPG",
    category: "Images",
    description: "Convert iPhone HEIC photos to compatible JPG format.",
    icon: ImageIcon,
    accept: ".heic,.heif",
    extensions: ["heic", "heif"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "jpg",
    contentType: "image/jpeg",
  },
  {
    id: "heic-to-png",
    title: "HEIC to PNG",
    category: "Images",
    description: "Convert iPhone HEIC photos to transparent PNG format.",
    icon: ImageIcon,
    accept: ".heic,.heif",
    extensions: ["heic", "heif"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "png",
    contentType: "image/png",
  },
  {
    id: "jpg-to-webp",
    title: "JPG to WEBP",
    category: "Images",
    description: "Optimize JPEG images for the web using WEBP format.",
    icon: ImageIcon,
    accept: ".jpg,.jpeg",
    extensions: ["jpg", "jpeg"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "webp",
    contentType: "image/webp",
  },
  {
    id: "png-to-webp",
    title: "PNG to WEBP",
    category: "Images",
    description: "Convert PNG images to WEBP format.",
    icon: ImageIcon,
    accept: ".png",
    extensions: ["png"],
    maxSize: 10 * 1024 * 1024,
    targetExt: "webp",
    contentType: "image/webp",
  },
  {
    id: "png-to-ico",
    title: "PNG to ICO",
    category: "Images",
    description: "Create website favicons (ICO) from PNG images.",
    icon: Layout,
    accept: ".png",
    extensions: ["png"],
    maxSize: 2 * 1024 * 1024,
    targetExt: "ico",
    contentType: "image/x-icon",
  },

  // TOOLS
  {
    id: "pdf-compressor",
    title: "PDF Compressor",
    category: "Tools",
    description: "Reduce the file size of your PDF documents.",
    icon: Minimize,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 50 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  },
  {
    id: "image-compressor",
    title: "Image Compressor",
    category: "Tools",
    description: "Compress JPG, PNG, or WEBP images without losing quality.",
    icon: Minimize,
    accept: ".jpg,.jpeg,.png,.webp",
    extensions: ["jpg", "jpeg", "png", "webp"],
    maxSize: 20 * 1024 * 1024,
    targetExt: "optimized",
    contentType: "image/jpeg",
  },
  {
    id: "pdf-merger",
    title: "PDF Merger",
    category: "Tools",
    description: "Combine multiple PDF files into one document.",
    icon: Layers,
    accept: ".pdf",
    extensions: ["pdf"],
    maxSize: 50 * 1024 * 1024,
    targetExt: "pdf",
    contentType: "application/pdf",
  }
];

export const getConverterById = (id: string) => CONVERTERS.find(c => c.id === id);
